RESUME_URL = "<YOUR RESUME URL>"
LINKEDIN_PROFILE_URL = "<LINKEDIN PROFILE URL>"
PHONE_NUMBER = "PHONE NUMBER"


SUBJECT_POSTFIX = " | 3 YoE | Python, Golang | LWD 30-Sept"

BODY_CLOSER = f"""\n
Here's my resume: {RESUME_URL}
Linkedin Profile: {LINKEDIN_PROFILE_URL}\n
Thanks,
<YOUR NAME>
{PHONE_NUMBER}
"""
FROM_MAIL = "<FROM_MAIL>"
